
public class BigTexts {

	public void printTitle() throws InterruptedException {
		

		System.out.println("Welcome, adventurer, to:");
		
		Thread.sleep(1000);
		
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("          ___  __  ______  ______  ___ ______     ________    ___    ___  _    ___  _________   _________  __________  _    ___");Thread.sleep(200);
		System.out.println("  The    /  / /_/ /_   _/ /_   _/ /  // ____/    /        \\  /  /   /  / / \\  /  / /  ______/  /  ______/ /         / / \\  /  /");Thread.sleep(200);
		System.out.println("        /  / __    /  /    /  /  /  // /_       /  __     / /  /   /  / /   \\/  / /  /        /  /       /  ____   / /   \\/  /");Thread.sleep(200);
		System.out.println("       /  / / /   /  /    /  /  /  //  _/      /  /  \\   / /  /   /  / /       / /  /  ____  /  /___    /  /   /  / /       /");Thread.sleep(200);
		System.out.println("      /  / / /   /  /    /  /  /  //  /___    /  /   /  / /  /   /  / /       / /  /  /_  / /  ____/   /  /   /  / /       /");Thread.sleep(200);
		System.out.println("     /  / /_/   /__/    /__/  /  //______/   /  /___/  / /  /___/  / /       / /  /    / / /  /       /  /___/  / /       /");Thread.sleep(200);
		System.out.println("    /  /____________________ /  /_______    /         / /         / /  /\\   / /  /____/ / /  /_____  /         / /  /\\   /");Thread.sleep(200);
		System.out.println("   /_______________________//__________/   /_________/ /_________/ /__/  \\_/ /_________/ /________/ /_________/ /__/  \\_/ ");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("A game by Mr Toto");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);		
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(4000);
		
	}
	
	public void printIntro() throws InterruptedException {
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                      Adventurer, this is a time of great distress..");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                               Coming back to your homeland after a long journey to find glory,");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                            you discover a devasted land..");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                   Nothing here looks like your childhood memories...");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                   In place of where once stood your father's castle,");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                        you find yourself in front of what seems to be an infinitly tall black tower.");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(4000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                        As you approach the tower, an even blacker door magicaly appears on the wall.");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(4000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                   Will you open it?");
		System.out.println("                                                          ...");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                        'y' or 'n'?");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
	}
	
	public void statExplained() {
		System.out.println("Character Creation:\n\n");
		System.out.println("Your character has primary stats, those are:\n");
		System.out.println("- Strength: how many items you can carry, your life and how hard you strike with melee\n\n"
						+"- Dexterity: your evade stat and how hard you strike with ranged\n\n"
						+"- Intelligence: your mana and the number and quality of skills you can lurn, also helps in some conversations\n\n"
						+"- Life: how much damage you can take before facing your death\n\n"
						+"- Mana: how many magic points you can use to cast magics\n");
		System.out.println("Those stats begin at 10 and you will have 15 points to distribute among them.\n");
		System.out.println("You also have secondary stats like 'armor' and 'magic armor',\n"
				+ "they are influenced by your strength and dexterity and the gears you equip\n\n");
		
	}

	public void losingText() throws InterruptedException {
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                  You do not open the door..");
		
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                           The tower vanishes in a shadowy effect");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                       You will never learn what hapened to your land,");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                    nor to your family..");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                  You disappoint us hero..");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                             Go back to your now miserable life.");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		
	}
	
	public void gameOver() throws InterruptedException {
	    System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("                  _________   _________  __    __     _________        ___________      ___  _________  _________  ");Thread.sleep(200);
		System.out.println("                 /  ______/  /  ___   / /  |  /  |   /  ______/       /           |    /  / /  ______/ / _____  /    ");Thread.sleep(200);
		System.out.println("                /  /        /  /  /  / /   | /   |  /  /__           /  ___   /|  |   /  / /  /__     / /____/ /      ");Thread.sleep(200);
		System.out.println("               /  /  ____  /  /  /  / /    |/    | /     /          /  /  /  / |  |  /  / /     /    /   _____/         ");Thread.sleep(200);
		System.out.println("              /  /  /_  / /  /__/  / /           |/   __/          /  /  /  /  |  | /  / /   __/    /    \\          ");Thread.sleep(200);
		System.out.println("             /  /____/ / /  ___   / /   /|   /|      /____        /  /__/  /   |  |/  / /   /____  /  /\\  \\             ");Thread.sleep(200);
		System.out.println("            /_________/ /__/  /__/ /___/ |__/ |__________/       /________/    |_____/ /________/ /__/  \\__\\                  ");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);		
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(4000);
	}
	
}
