
public class BigTexts {

	public void printTitle() throws InterruptedException {
		

		System.out.println("Welcome, adventurer, to:");
		
		Thread.sleep(1000);
		
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("          ___  __  ______  ______  ___ ______     ________    ___    ___  _    ___  _________   _________  __________  _    ___");Thread.sleep(200);
		System.out.println("  The    /  / /_/ /_   _/ /_   _/ /  // ____/    /        \\  /  /   /  / / \\  /  / /  ______/  /  ______/ /         / / \\  /  /");Thread.sleep(200);
		System.out.println("        /  / __    /  /    /  /  /  // /_       /  __     / /  /   /  / /   \\/  / /  /        /  /       /  ____   / /   \\/  /");Thread.sleep(200);
		System.out.println("       /  / / /   /  /    /  /  /  //  _/      /  /  \\   / /  /   /  / /       / /  /  ____  /  /___    /  /   /  / /       /");Thread.sleep(200);
		System.out.println("      /  / / /   /  /    /  /  /  //  /___    /  /   /  / /  /   /  / /       / /  /  /_  / /  ____/   /  /   /  / /       /");Thread.sleep(200);
		System.out.println("     /  / /_/   /__/    /__/  /  //______/   /  /___/  / /  /___/  / /       / /  /    / / /  /       /  /___/  / /       /");Thread.sleep(200);
		System.out.println("    /  /____________________ /  /_______    /         / /         / /  /\\   / /  /____/ / /  /_____  /         / /  /\\   /");Thread.sleep(200);
		System.out.println("   /_______________________//__________/   /_________/ /_________/ /__/  \\_/ /_________/ /________/ /_________/ /__/  \\_/ ");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("A game by Mr Toto");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);		
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(200);
		System.out.println("");Thread.sleep(4000);
		
	}
	
	public void printIntro() throws InterruptedException {
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                      Adventurer, this is a time of great distress..");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                               Coming back to your homeland after a long journey to find glory,");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                            you discover a devasted land..");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                   Nothing here looks like your childhood memories...");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                   In place of where once stood your father's castle,");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                        you find yourself in front of what seems to be an infinitly tall black tower.");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(4000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                        As you approach the tower, an even blacker door magicaly appears on the wall.");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(4000);
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                   Will you open it?");
		System.out.println("                                                          ...");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");Thread.sleep(3000);
	}
	
}
